### PR TITLE
No blank messages

### PR DESCRIPTION
**Pull request by aplusjm8**
LAD

### CODE REVIEW

**Comment by TETYYS** [comment]
String.IsNullOrWhiteSpace anyone?

**Comment by emcf** [comment]
What's the difference between that and String.IsNullOrEmpty? I actually don't know.
Also, good idea.

**Comment by TETYYS** [comment]
​

**Comment by TETYYS** [comment]
I think it prevents posts like this too:

**Comment by TETYYS** [comment]
​

**Pull request merged**
